///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace POC_WinCalculator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the POC_WinCalculatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("689ea1e5-0d7f-4346-9489-e9719b0c17a3")]
    public partial class POC_WinCalculatorRepository : RepoGenBaseFolder
    {
        static POC_WinCalculatorRepository instance = new POC_WinCalculatorRepository();
        POC_WinCalculatorRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the POC_WinCalculatorRepository element repository.
        /// </summary>
        [RepositoryFolder("689ea1e5-0d7f-4346-9489-e9719b0c17a3")]
        public static POC_WinCalculatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public POC_WinCalculatorRepository() 
            : base("POC_WinCalculatorRepository", "/", null, 0, false, "689ea1e5-0d7f-4346-9489-e9719b0c17a3", ".\\RepositoryImages\\POC_WinCalculatorRepository689ea1e5.rximgres")
        {
            _calculator = new POC_WinCalculatorRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

        string _num1 = "";

        /// <summary>
        /// Gets or sets the value of variable num1.
        /// </summary>
        [TestVariable("838d704e-b353-4fa2-97e5-0b7f9c013489")]
        public string num1
        {
            get { return _num1; }
            set { _num1 = value; }
        }

        string _operation = "";

        /// <summary>
        /// Gets or sets the value of variable operation.
        /// </summary>
        [TestVariable("871608bd-1331-4ab3-9b56-fbabfa2f0ae0")]
        public string operation
        {
            get { return _operation; }
            set { _operation = value; }
        }

        string _num2 = "";

        /// <summary>
        /// Gets or sets the value of variable num2.
        /// </summary>
        [TestVariable("386d27c9-6e17-4a1b-ad21-9c7abbdb5b55")]
        public string num2
        {
            get { return _num2; }
            set { _num2 = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("689ea1e5-0d7f-4346-9489-e9719b0c17a3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("15ba4fd4-6bc3-42fd-b1a2-15e1fd6d8064")]
        public virtual POC_WinCalculatorRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class POC_WinCalculatorRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("15ba4fd4-6bc3-42fd-b1a2-15e1fd6d8064")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num_1Info;
            RepoItemInfo _operationInfo;
            RepoItemInfo _num_2Info;
            RepoItemInfo _num5buttonInfo;
            RepoItemInfo _textcontainerInfo;
            RepoItemInfo _equalbuttonInfo;
            RepoItemInfo _normaloutputInfo;
            RepoItemInfo _calculatorresultsInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "15ba4fd4-6bc3-42fd-b1a2-15e1fd6d8064", "")
            {
                _num_1Info = new RepoItemInfo(this, "Num_1", "?/?/container[@automationid='NumberPad']/button[@automationid='num'+$num1+'Button']", 30000, null, "16f7c44b-2654-4cb3-a406-2c5b2519380a");
                _operationInfo = new RepoItemInfo(this, "Operation", "?/?/container[@automationid='StandardOperators']/button[@automationid=$operation]", 30000, null, "1e522da6-152f-4cf5-b466-1e5da19fc070");
                _num_2Info = new RepoItemInfo(this, "Num_2", "?/?/container[@automationid='NumberPad']/button[@automationid='num'+$num2+'Button']", 30000, null, "ccd3f73f-c1ff-4656-a2aa-3c6f9947b9a4");
                _num5buttonInfo = new RepoItemInfo(this, "Num5Button", "?/?/container[@automationid='NumberPad']/button[@automationid='num5Button']", 30000, null, "a37e494a-305a-474e-a964-2f00bb2b97b3");
                _textcontainerInfo = new RepoItemInfo(this, "TextContainer", "?/?/text[@automationid='CalculatorResults']/container[@automationid='TextContainer']", 30000, null, "3ec77a4b-85be-4df5-92aa-742de16b368d");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", "?/?/container[@automationid='StandardOperators']/button[@automationid='equalButton']", 30000, null, "c3efbfac-5506-4367-8282-669ccfb9346b");
                _normaloutputInfo = new RepoItemInfo(this, "NormalOutput", "?/?/text[@automationid='CalculatorResults']/?/?/text[@automationid='NormalOutput']", 30000, null, "3d073390-8713-4302-a212-58f48d85c2ec");
                _calculatorresultsInfo = new RepoItemInfo(this, "CalculatorResults", "?/?/text[@automationid='CalculatorResults']", 30000, null, "e68a3e37-4542-4450-aeca-0ce3c52c8390");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("15ba4fd4-6bc3-42fd-b1a2-15e1fd6d8064")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("15ba4fd4-6bc3-42fd-b1a2-15e1fd6d8064")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num_1 item.
            /// </summary>
            [RepositoryItem("16f7c44b-2654-4cb3-a406-2c5b2519380a")]
            public virtual Ranorex.Button Num_1
            {
                get
                {
                    return _num_1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num_1 item info.
            /// </summary>
            [RepositoryItemInfo("16f7c44b-2654-4cb3-a406-2c5b2519380a")]
            public virtual RepoItemInfo Num_1Info
            {
                get
                {
                    return _num_1Info;
                }
            }

            /// <summary>
            /// The Operation item.
            /// </summary>
            [RepositoryItem("1e522da6-152f-4cf5-b466-1e5da19fc070")]
            public virtual Ranorex.Button Operation
            {
                get
                {
                    return _operationInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Operation item info.
            /// </summary>
            [RepositoryItemInfo("1e522da6-152f-4cf5-b466-1e5da19fc070")]
            public virtual RepoItemInfo OperationInfo
            {
                get
                {
                    return _operationInfo;
                }
            }

            /// <summary>
            /// The Num_2 item.
            /// </summary>
            [RepositoryItem("ccd3f73f-c1ff-4656-a2aa-3c6f9947b9a4")]
            public virtual Ranorex.Button Num_2
            {
                get
                {
                    return _num_2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num_2 item info.
            /// </summary>
            [RepositoryItemInfo("ccd3f73f-c1ff-4656-a2aa-3c6f9947b9a4")]
            public virtual RepoItemInfo Num_2Info
            {
                get
                {
                    return _num_2Info;
                }
            }

            /// <summary>
            /// The Num5Button item.
            /// </summary>
            [RepositoryItem("a37e494a-305a-474e-a964-2f00bb2b97b3")]
            public virtual Ranorex.Button Num5Button
            {
                get
                {
                    return _num5buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num5Button item info.
            /// </summary>
            [RepositoryItemInfo("a37e494a-305a-474e-a964-2f00bb2b97b3")]
            public virtual RepoItemInfo Num5ButtonInfo
            {
                get
                {
                    return _num5buttonInfo;
                }
            }

            /// <summary>
            /// The TextContainer item.
            /// </summary>
            [RepositoryItem("3ec77a4b-85be-4df5-92aa-742de16b368d")]
            public virtual Ranorex.Container TextContainer
            {
                get
                {
                    return _textcontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TextContainer item info.
            /// </summary>
            [RepositoryItemInfo("3ec77a4b-85be-4df5-92aa-742de16b368d")]
            public virtual RepoItemInfo TextContainerInfo
            {
                get
                {
                    return _textcontainerInfo;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("c3efbfac-5506-4367-8282-669ccfb9346b")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("c3efbfac-5506-4367-8282-669ccfb9346b")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }

            /// <summary>
            /// The NormalOutput item.
            /// </summary>
            [RepositoryItem("3d073390-8713-4302-a212-58f48d85c2ec")]
            public virtual Ranorex.Text NormalOutput
            {
                get
                {
                    return _normaloutputInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NormalOutput item info.
            /// </summary>
            [RepositoryItemInfo("3d073390-8713-4302-a212-58f48d85c2ec")]
            public virtual RepoItemInfo NormalOutputInfo
            {
                get
                {
                    return _normaloutputInfo;
                }
            }

            /// <summary>
            /// The CalculatorResults item.
            /// </summary>
            [RepositoryItem("e68a3e37-4542-4450-aeca-0ce3c52c8390")]
            public virtual Ranorex.Text CalculatorResults
            {
                get
                {
                    return _calculatorresultsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CalculatorResults item info.
            /// </summary>
            [RepositoryItemInfo("e68a3e37-4542-4450-aeca-0ce3c52c8390")]
            public virtual RepoItemInfo CalculatorResultsInfo
            {
                get
                {
                    return _calculatorresultsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
